### ISSUE TITLE
Problem with Ollydbg2 api Decodeknownbyaddr

### ISSUE THREAD

**Issue by Cishanduwang** [a1ext/labeless#64]
### Environment
python2.7-32
ollydbg2.01
#### Debugger-side information

| Question                         | Answer
|----------------------------------|--------------------
| OS version (client)              | 10
| Plugin version                   | 1.1.6.0
| `labeless` python module version | 1.1.6.0
| Debugger type                    | OllyDbg 2.01

### Problem Description
I am writing debugger side script.
I try to call api Decodeknownbyaddr:
```python
......
rettype = ctypes.create_unicode_buffer(api.SHORTNAME)
print api.Decodeknownbyaddr(threads.GetEip(), None, None, rettype, None, -1, 0)
......
```
The define of Decodeknownbyaddr is:
https://www.ollydbg.de/Help/Decodeknownbyaddr.htm
```
int Decodeknownbyaddr(ulong addr,t_procdata *pd,t_argdec adec[NARG],wchar_t *rettype,wchar_t *name,int nexp,int follow);
```
After run this code , i got an error :
```
Traceback (most recent call last):
  File "<string>", line 39, in <module>
  File "C:\Python27\lib\site-packages\labeless\backend\ollydbg20\ollyapi2.py", line 4248, in Decodeknownbyaddr
    return _ollyapi2.Decodeknownbyaddr(*args)
TypeError: in method 'Decodeknownbyaddr', argument 4 of type 'wchar_t *'

```
i think ctypes.create_unicode_buffer will create a c_wchar array equal to wchar_t * in c. same as your function in utils.py(get_user_comments):
```python
def get_user_comments(start=0, end=0xffffffff):
    """
    Get User-defined comments list
    :param start: Address of a start range
    :param end: Address of an end
    :return: list of dict(ea=xx, v=yy)
    """
    p = api.new_ulong_p()
    try:
        api.ulong_p_assign(p, start)
        arr = ctypes.create_unicode_buffer(api.TEXTLEN)

        api.Startnextdata(start, end, api.NM_COMMENT)
        rv = []
        while api.FindnextnameW(p, arr, api.NM_COMMENT):
            s = arr.value.rstrip('\0')
            rv.append({'ea': api.ulong_p_value(p), 'v': s})
        return rv
    finally:
        if p:
            api.delete_ulong_p(p)
```
if i set argument 4 to None, this api works fine. Did I make a mistake?

by the way, how to construct 't_argdec adec[NARG]' in python?

thank you.

**Comment by a1ext** [comment]
hi @Cishanduwang , thanks for submitting an issue. I checked the generated swig wrapper code and it looks like while parsing arguments of `wchar_t*` it expects an unicode string or convertable to `pwchar` swig type pointer and that's wrong approach because string in python is immutable... I think I add some swig annotation to allow passing ctypes unicode buffer, let me play with the swig and I will update here

**Comment by a1ext** [comment]
ok, I managed to make it work but it requires new `labeless` python  module update and a new plugins to be deployed to your Olly and IDA, I will include the fix into next release.
![image](https://github.com/user-attachments/assets/b7ce173e-1178-4d56-90fc-6513d3630664)

![image](https://github.com/user-attachments/assets/5cee90e6-5164-44a5-af51-4449479cd407)

Btw, would you like to participate in beta testing of next release (IDA 9 support + migration to Python 3)? If so, I uploaded a fixed bundle, you can find the link here: https://github.com/a1ext/labeless/issues/63#issuecomment-2564766767

**Comment by Cishanduwang** [comment]
Hi a1ext, Happy new year. Thank you for your reply. 

Yes, I am willing to try the python3 version of labeless. Current python3 version is 1.1.7.0. Has this bug been fixed in this version?

**Comment by a1ext** [comment]
hi @Cishanduwang, yes the bug has been fixed in that build, could try and tell me if it works for you? on the screenshots above I showed that even Decodeknownbyname now works and added `api.t_argdecArray` type for convenience

**Comment by a1ext** [comment]
the initial problem that Olly 2 SDK has no documentation which arguments like `wchar_t*` are `input` and which are `output`, so by default SWIG (a library which provides python wrappers over C/C++ code) treats wchar_t* as `input` arguments.
So to allow us to use unicode buffers we need to mark those arguments as mutable during SWIG wrapper generation.
For me that is manual work to find the docs about  API and mark it as mutable. I would request from you if you spot some API should have some arguments as output for types like wchar_t* let me know and I will update all wrappers and bindings.
Thanks :)

**Comment by Cishanduwang** [comment]
Okay, if i spot these APIs, I will let you know.

**Comment by Cishanduwang** [comment]
Hi, @a1ext. It seems that Ollydbg2 can't load the 1.1.7.0 plugin. I have set the plugin path, and i use 1.1.6.0 version of plugin works well but 1.1.7.0 not.

**Comment by a1ext** [comment]
please check the log window for any errors to understand why it is not loading

**Comment by Cishanduwang** [comment]
Hi,@a1ext , there is no log shown in log window when i try to load 1.1.7.0 dll.

So, i fall back to 1.1.6.0 and add argdecArray in ollapi2-swig.i file:
```
......
%array_class(t_argdec, t_argdecArray)
......
```
Mark rettype, name mutiable in Plugin-swig.h:
```c
......
%pybuffer_mutable_string(wchat_t *rettype)
%pybuffer_mutable_string(wchat_t *name)
stdapi (int)     Decodeknownbyaddr(ulong addr,t_procdata *pd,
                   t_argdec adec[NARG],wchar_t *rettype,wchar_t *name,
                   int nexp,int follow);
%typemap(in) wchar_t *rettype;
%typemap(in) wchar_t *name;
......
```

Then regenerate swig and recompile olldbg2 plugin.
Now, rettype and name works well. But members in struct t_argdec cant be assign properly.
```python
# Get arg num
ret_type_unuse = ctypes.create_unicode_buffer(api.SHOUTNAME)
fn_name_unuse = ctypes.create_unicode_buffer(api.TEXTLEN)
arg_num = api.Decodeknownbyaddr(threads.GetEip(), None, None, ret_tyoe_unuse, fn_name_unuse, -1, 0)
if arg_num != -1:
    ret_type = ctypes.create_unicode_buffer(api.SHOUTNAME)
    fn_name = ctypes.create_unicode_buffer(api.TEXTLEN)
    argdec_array = api.t_argdecArray(api.NARG)
    for i in range(arg_num):
        p_reg = api.Threadregisters(threads.GetCpuThreadId())
        r = api.ulongArray.frompointer(p_reg.r)
        argdec_array[i].mode = api.ADEC_VALID  # api.ADEC_VALID == 1
        argdec_array[i].pushaddr = 0
        print "original mode :%d -> assigned:%d" % (api.ADEC_VALID, argdec_array[i].mode)
        print "original pushaddr: %d -> assigned:%d" % (0, argdec_array[i].pushaddr)
```
The original value of mode and assigned value of mode must be the same. But the output is not. Same situation in property pushaddr. Did i make a mistake?

**Comment by a1ext** [comment]
do other arrays behave the same? btw, why are you assigning to argdec, are there some write API which can apply provided argdec?

**Comment by Cishanduwang** [comment]
According to Decodeknownbyaddr's definition. 
https://web.archive.org/web/20220120175219/http://ollydbg.de/Help/Decodeknownbyaddr.htm

>If you want to decode function's arguments to text, you must read these arguments from the stack and supply them to Decodeknownbyaddr(). On entry, you only need to set adec[].mode and adec[].value and zero adec[].pushaddr. adec[0] corresponds to the first argument (pushed last, with the lowest stack address). Note that ESP at the entry points to the address of return and first argument is at ESP+4.

**Comment by a1ext** [comment]
it seems like SWIG makes wrappers which return a copy of value (structure content) via `__getitem__` (`swigwin-3.0.2\Lib\python\carrays.i`):
```
%define %array_class(TYPE,NAME)
#if defined(SWIGPYTHON_BUILTIN)
  %feature("python:slot", "sq_item", functype="ssizeargfunc") NAME::__getitem__;
  %feature("python:slot", "sq_ass_item", functype="ssizeobjargproc") NAME::__setitem__;

%inline %{
typedef struct {
    TYPE *el;
} NAME;
%}

%extend NAME {

  NAME(size_t nelements) {
      NAME *arr = %new_instance(NAME);
      arr->el = %new_array(nelements, TYPE);
      return arr;
  }

  ~NAME() {
      %delete_array(self->el);
      %delete(self);
  }
  
  TYPE __getitem__(size_t index) {
      return self->el[index];
  }

  void __setitem__(size_t index, TYPE value) {
      self->el[index] = value;
  }

  TYPE * cast() {
      return self->el;
  }

  static NAME *frompointer(TYPE *t) {
      return %reinterpret_cast(t, NAME *);
  }
};

%types(NAME = TYPE);

#else
  %array_class_wrap(TYPE,NAME,__getitem__,__setitem__)
#endif
%enddef

%include <typemaps/carrays.swg>
```

 it means when you do `x[0]` -  the copy of 0-th object is returned to an expression and then the assignment is made to the temporary copy of a struct... as a workaround I suggest to assign everything to some temp instance of `t_argdec` and then assign it to all the elements of array

**Comment by a1ext** [comment]
I'm thinking about adding some memory diff functionality, what do you think will it be useful? like to request a diff of memory from IDA DB with actual mapped in a debugger memory

**Comment by Cishanduwang** [comment]
> it means when you do x[0] - the copy of 0-th object is returned to an expression and then the assignment is made to the temporary copy of a struct... as a workaround I suggest to assign everything to some temp instance of t_argdec and then assign it to all the elements of array

It works, thank you very much.

> I'm thinking about adding some memory diff functionality, what do you think will it be useful? like to request a diff of memory from IDA DB with actual mapped in a debugger memory

If this functionality will help analyze function parameters that can only be determined by dynamic debugging. I think it's useful.

Questions about this function has been solved, so i will close this issue, thank you again.
